---
title: "Waffle Charts"
output: html_document
date: "2024-05-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Introduction**
This project shows the visualization of Breaking Bad series data using Waffle Chart 


```{r}
# Import the libraries
library(tidyverse) # For data transformation and manipulation
library(ggplot2) # For data visualisation
library(tidyverse)
library(showtext)
library(ggtext)
library(waffle) # For data visualisation
library(MetBrewer)
library(patchwork)

```


# **Loading data into R Environment**

```{r}
# Load the data
path = "C:/Users/Hp/Desktop/IBK - TEMP/Breaking Bad Dataset.csv"

breaking_bad <- read_csv(path) 

###### Exploratory Data Analysis

# Check the first few rows of the data
head(breaking_bad)

# Check the no. of rows and columns of the data
dim(breaking_bad)

# Check information of the data
glimpse(breaking_bad)
```

# **Data Preparation**

```{r}
df <- breaking_bad|> 
  select(c(Season,Episode,Duration_minutes))|> group_by(Season,Episode)|>
  summarise(duration = sum(Duration_minutes))
df
df<- df|>as.data.frame()

df
```

# **Text Preparation**

```{r}

font_add_google("Outfit", "title_font")
font_add_google("Cabin", "body_font")
showtext_auto()

title_font <- "title_font"
body_font <- "body_font"

```


# **Data Visualization**

```{r}
graph = ggplot(df, aes(fill = Season, values = duration)) +
   geom_waffle(color = "white", size = 0.25, n_rows = 10, flip = TRUE) +
  facet_wrap(~Episode, nrow = 1, strip.position = "bottom") +
  scale_x_discrete() + 
  scale_y_continuous(labels = function(x) x * 10, # make this multiply the same as n_rows
                     expand = c(0,0))+
  scale_fill_met_d("VanGogh2", direction=1)+
  labs(title = "Breaking Bad Series had a total of 5 Seasons", x = "Episodes", y="Duration in Minutes",
       
       subtitle =  "Season 1 had the lowest episodes:7\nSeason 5 had the highest episodes:16\nSeason 5 ran for the highest number of minutes:  776 minutes\nBoth seasons 2 and 3 ran for exactly the same number of minutes: 611 minutes",
       caption = "Graphic: Ibikunle Gabriel|Data Source: Kaggle")+
  theme_minimal()+
  theme(
        axis.text.x = element_text(family = body_font, size=12),
    axis.text.y = element_text(family = body_font, size=12),
  # Legend
  legend.position = "right",
  legend.title = element_text("Season"),
  legend.spacing = unit(0.5, 'cm'),
  legend.key.height= unit(0.5, 'cm'),
  legend.key.width= unit(0.7, 'cm'),
  legend.text = element_text(family = body_font,
                             size=13,
                             face = 'plain',
                             color = "grey10"),
  
  # TITLE
  plot.title.position = "plot",
  plot.title = element_textbox(margin = margin(20, 0, 10, 0),
                               size = 30,
                               family = title_font,
                               face = "bold",
                               width = unit(55, "lines")),
  
  # SUB-TITLE
  plot.subtitle = element_text(margin = margin(10, 0, 20, 0),
                            size = 16,
                            family = body_font,
                            color = "grey15"),
  # Caption
  plot.caption.position = "plot", 
  plot.caption = element_text(family=body_font,
                              face="bold",
                              size=16, 
                              color="grey40",
                              hjust=.5, 
                              margin=margin(20,0,0,0)),
  
  plot.background = element_rect(color="white", fill="white"),
  plot.margin = margin(20, 40, 20, 40)
)

showtext_opts(dpi = 320)
ggsave(
  "C:/Users/Hp/Desktop/IBK - TEMP/breaking_bad.png", 
  dpi=320, width = 12, height = 9
)
showtext_auto(FALSE)
 
graph
```



























